# Uncomment this line to define a global platform for your project
platform :ios, "5.1"           

xcodeproj 'CRAnimationTabBarDemo'
workspace 'CRAnimationTabBarDemo'

pod 'CRAnimationTabBar', :path => '..'
